### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by xtho25** [Mysttt/Discord-Giveaway-Bot#2]
So, i am working on replit and a have this problem:
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'

idk how to download ramuel

**Comment by 222ryan** [comment]
Hey,

Sorry for the delayed response. To install ruamel, use 'pip install ruamel.yaml'

Let me know if this works!
